### PR TITLE
Use the json_options for serializing also.

### PR DESCRIPTION
**Pull request by runarbu**
It is good to be able to set flags like pretty and indent when making json.

### CODE REVIEW

**Comment by jjn1056** [comment]
Hey,

this looks ok but not sure if the options for encode and decode can be used interchangeable.   can you help me verify?

**Comment by runarbu** [comment]
That the json option may not be interchangeable is a good point @jjn1056 . If they are interchangeable is hard to verify, and I can also not guarantee that the underlying json library will not change the behavior in the future.

I suggest that we err on the side of caution, and use different options for input and output.

I will do the change and resend the pull request.

Do you have any preferences for the name for this new option? “json_options_out”, “json_options_encode”?

**Comment by perl-catalyst-sync** [comment]
I think json_options_encode sounds pretty good!  -jnap

**Comment by runarbu** [comment]
Great. json_options_encode it is then. I have sent a new pull request as #9 :-)

**Pull request closed without merging**
